# Generated by Django 5.0 on 2024-01-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='ammount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
