# Generated by Django 5.0 on 2024-01-13 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='watchlist', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('auctions', models.ManyToManyField(blank=True, null=True, related_name='watchlist', to='auctions.auction')),
            ],
        ),
    ]
