# Generated by Django 5.0 on 2024-01-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_price_auction_initialbid_auction_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to='auctions.auction'),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
