# Generated by Django 5.0 on 2024-01-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_user_watchlist_delete_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='initialBid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
        migrations.AddField(
            model_name='auction',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='auctions', to='auctions.bid'),
        ),
    ]
