# Generated by Django 5.0 on 2024-01-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auction_initialbid_remove_bid_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bids',
            field=models.ManyToManyField(blank=True, null=True, related_name='auctions', to='auctions.bid'),
        ),
    ]
