# Generated by Django 5.0 on 2024-02-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '✨'), (2, '✨✨'), (3, '✨✨✨'), (4, '✨✨✨✨'), (5, '✨✨✨✨✨')], default=3),
            preserve_default=False,
        ),
    ]
